name: ShellCheck

on:
  push:
    branches: [ main ]
    paths:
      - '**.sh'
      - '**.bash'
      - '**.zsh'
  pull_request:
    branches: [ main ]
    paths:
      - '**.sh'
      - '**.bash'
      - '**.zsh'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        format: gcc
        severity: warning
      env:
        SHELLCHECK_OPTS: -e SC1091 -e SC2034